#!/usr/bin/env bash
# Generate the Ansible inventory from provisioned VMs.
# Reads stdin lines: "<short> <role> <name> <ssh_port> <lab_ip>"
# Writes ansible/inventory/hosts.generated.yaml
# Kept compatible with the bash 3.2 that ships with macOS (no associative arrays).
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

load_config
mkdir -p "$(dirname "$INVENTORY_FILE")"

# Buffer stdin so we can iterate it twice (hosts, then groups).
rows="$(cat)"

{
  echo "# Generated by scripts/gen-inventory.sh. Do not edit by hand."
  echo "all:"
  echo "  vars:"
  echo "    ansible_user: ${LAB_USER}"
  echo "    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'"
  echo "  hosts:"
  while read -r short role name port lab_ip; do
    [[ -z "$short" ]] && continue
    echo "    ${short}:"
    echo "      ansible_host: 127.0.0.1"
    echo "      ansible_port: ${port}"
    echo "      lab_ip: ${lab_ip}"
    echo "      vm_name: ${name}"
  done <<<"$rows"

  echo "  children:"
  # One group per role. The group name is derived from the role, not equal to
  # it, for two reasons Ansible warns about otherwise: a role like 'vuln-web'
  # is not a valid group identifier (hyphens), and a host and group with the
  # same name (short name == role, e.g. attacker:attacker) collide. Prefixing
  # 'role_' and mapping '-' to '_' avoids both. The playbook targets these
  # 'role_*' groups; --tags still uses the plain role names.
  # Unique roles, preserving first-seen order.
  roles="$(printf '%s\n' "$rows" | awk 'NF{print $2}' | awk '!seen[$0]++')"
  while read -r role; do
    [[ -z "$role" ]] && continue
    group="role_$(printf '%s' "$role" | tr '-' '_')"
    echo "    ${group}:"
    echo "      hosts:"
    while read -r short r2 name port lab_ip; do
      [[ "$r2" == "$role" ]] && echo "        ${short}:"
    done <<<"$rows"
  done <<<"$roles"
} > "$INVENTORY_FILE"

ok "Inventory written: ${INVENTORY_FILE}"
