#!/usr/bin/env bash
# Generate the Ansible inventory from provisioned VMs.
# Reads stdin lines: "<short> <role> <name> <ssh_port> <lab_ip>"
# Writes ansible/inventory/hosts.generated.yaml
# Kept compatible with the bash 3.2 that ships with macOS (no associative arrays).
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

load_config
mkdir -p "$(dirname "$INVENTORY_FILE")"

# Buffer stdin so we can iterate it twice (hosts, then groups).
rows="$(cat)"

{
  echo "# Generated by scripts/gen-inventory.sh. Do not edit by hand."
  echo "all:"
  echo "  vars:"
  echo "    ansible_user: ${LAB_USER}"
  echo "    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'"
  echo "  hosts:"
  while read -r short role name port lab_ip; do
    [[ -z "$short" ]] && continue
    echo "    ${short}:"
    echo "      ansible_host: 127.0.0.1"
    echo "      ansible_port: ${port}"
    echo "      lab_ip: ${lab_ip}"
    echo "      vm_name: ${name}"
  done <<<"$rows"

  echo "  children:"
  # One group per role, ALWAYS, even when all its VMs are state=off: an empty
  # group makes the playbook's pattern match (and skip silently) instead of
  # warning. Names are role_<role> with '-' to '_': 'vuln-web' is not a valid
  # group name, and a host and group may not share a name (attacker:attacker).
  # Unique roles from the fleet, preserving first-seen order.
  roles=""
  for entry in "${LAB_VMS[@]}"; do
    parse_vm_entry "$entry"
    roles+="${VM_ROLE}"$'\n'
  done
  roles="$(printf '%s' "$roles" | awk '!seen[$0]++')"
  while read -r role; do
    [[ -z "$role" ]] && continue
    group="role_$(printf '%s' "$role" | tr '-' '_')"
    echo "    ${group}:"
    echo "      hosts:"
    while read -r short r2 name port lab_ip; do
      [[ "$r2" == "$role" ]] && echo "        ${short}:"
    done <<<"$rows"
  done <<<"$roles"
} > "$INVENTORY_FILE"

ok "Inventory written: ${INVENTORY_FILE}"
